## Copyright (c) 2024, 2025, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "app.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      securityContext:
        fsGroup: 10001
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - name: server-port
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ include "getPath" . }}v1/liveness
              port: server-port
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: {{ include "getPath" . }}v1/readiness
              port: server-port
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 15
            failureThreshold: 6
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.adb.enabled }}
            - name: TNS_ADMIN
              value: /app/tns_admin
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.adb.authN.secretName | quote }}
                  key: {{ .Values.adb.authN.usernameKey | default "username" | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.adb.authN.secretName | quote }}
                  key: {{ .Values.adb.authN.passwordKey | default "password" | quote }}
            - name: DB_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.adb.authN.secretName | quote }}
                  key: {{ .Values.adb.authN.serviceKey | default "service" | quote }}
            {{- $mtlsWallet := include "getMtlsWallet" . | fromJson }}
            {{- if $mtlsWallet.secretName }}
            - name: DB_WALLET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $mtlsWallet.secretName | quote }}
                  key: {{ $mtlsWallet.secretKey | quote }}
            {{ else }}
            - name: DB_WALLET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "app.fullname" . }}-adb-wallet-pass-{{ .Release.Revision }}
                  key: {{ include "app.fullname" . }}-adb-wallet-pass-{{ .Release.Revision }}
            {{- end }}
            {{- end }}
            - name: API_SERVER_PORT
              value: "8000"
            - name: API_SERVER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.api.secretName | default (printf "%s-api-key" (include "release.name" .)) }}
                  key: {{ .Values.global.api.secretKey | default "apiKey" }}
            {{- with .Values }}
            {{- if .models }}
            {{- if and .models.openAI .models.openAI.secretName }}
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .models.openAI.secretName }}
                  key: {{ .models.openAI.secretKey | default "apiKey" }}
            {{- end }}
            {{- if and .models.perplexity .models.perplexity.secretName }}
            - name: PPLX_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .models.perplexity.secretName }}
                  key: {{ .models.perplexity.secretKey | default "apiKey" }}
            {{- end }}
            {{- if and .models.cohere .models.cohere.secretName }}
            - name: COHERE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .models.cohere.secretName }}
                  key: {{ .models.cohere.secretKey | default "apiKey" }}
            {{- end }}
            {{- if and .models.huggingface .models.huggingface.urlPort }}
            - name: ON_PREM_HF_URL
              value: {{ .models.huggingface.urlPort }}
            {{- end }}
            {{- if and .models.ollama .models.ollama.enabled }}
            - name: ON_PREM_OLLAMA_URL
              value: {{ include "ollama.serviceUrl" . }}
            {{- end }}
            {{- end }}
            {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: "/app/tmp"
            {{- if .Values.adb.enabled }}
            - name: tns-admin
              mountPath: /app/tns_admin
            {{- end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        {{- if .Values.adb.enabled }}
        - name: tns-admin
          secret:
            {{- $tnsAdmin := include "getTnsAdmin" . | fromJson }}
            {{- if $tnsAdmin.secretName }}
            secretName: {{ $tnsAdmin.secretName | quote }}
            {{ else }}
            secretName: {{ include "app.fullname" . }}-adb-tns-admin-{{ .Release.Revision }}
            {{- end }}
        {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
