## Copyright (c) 2024, 2025, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.

apiVersion: v2
name: oai-client
description: A Helm chart Oracle AI Explorer for Apps - GUI
type: application
version: 0.1.0
appVersion: "0.1.0"
maintainers:
  - name: Oracle
    email: obaas_ww@oracle.com
    url: https://github.com/oracle-samples/oaim-sandbox
