## Copyright (c) 2024, 2025, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oaim.fullname" . }}-st-config
  labels: 
    {{- include "oaim.labels" . | nindent 4 }}
data:
  config.toml: |
    [global]
    disableWidgetStateDuplicationWarning = true

    [browser]
    gatherUsageStats = false
    serverAddress = "0.0.0.0"

    [server]
    port = "8501"
    cookieSecret = "{{ randAlphaNum 32 | b64enc }}"
    headless = true
    fileWatcherType = "none"
    {{- $path := include "getPath" . }}
    {{- if ne $path "/" }}
    baseUrlPath = {{ include "getPath" . | quote }}
    {{- end }}

    [client]
    toolbarMode = "minimal"