server:
  servlet:
    context-path: /v1
spring:
  datasource:
    url: ${DB_DSN}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  ai:
    vectorstore:
      oracle:
        distance-type: ${DISTANCE_TYPE}
        remove-existing-vector-store-table: True
        initialize-schema: True
        index-type: None
    openai:
      base-url: {OPENAI_URL}
      api-key:
        chat:
          options:
            temperature: {OP_TEMPERATURE}
            frequencyPenalty: {OP_FREQUENCY_PENALTY}
            presencePenalty: {OP_PRESENCE_PENALTY}
            maxTokens: {OP_MAX_TOKENS}
            topP: {OP_TOP_P}
      chat:
        options:
          temperature: 0.0
          model: ${OPENAI_CHAT_MODEL}
          maxTokens : 200
      embedding:
        options:
          model: ${OPENAI_EMBEDDING_MODEL}
    ollama:
      chat:
        options:
          top-p: {OL_TOP_P}
          presence-penalty: {OL_PRESENCE_PENALTY}
          frequency-penalty: {OL_FREQUENCY_PENALTY}
          temperature: {OL_TEMPERATURE}
          num-predict: {OL_MAX_TOKENS}
      base-url: ${OLLAMA_BASE_URL}
      embedding:
        options: 
          model: ${OLLAMA_EMBEDDING_MODEL}
      chat:
        options: 
          model: ${OLLAMA_CHAT_MODEL}
aims:
  context_instr: ${CONTEXT_INSTR}
  vectortable:
    name: ${VECTOR_STORE}
  rag_params: 
    search_type: Similarity
    top_k: ${TOP_K}

